# Generated by Django 6.1 on 2026-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=10),
        ),
    ]
