# Generated by Django 6.1 on 2026-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0005_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('kids', 'Kids'), ('accessories', 'Accessories')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('X', 'X'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4),
        ),
    ]
